# Generated by Django 4.2.7 on 2025-05-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='prescription_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
