# Generated by Django 4.2.7 on 2025-05-28 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_prescription_prescription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='doctor_department',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
