# Generated by Django 4.2.7 on 2025-05-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(blank=True, max_length=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], max_length=9, null=True)),
                ('date', models.DateField()),
                ('transaction_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
