# Generated by Django 4.2.7 on 2025-05-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transactions_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='doctor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
