# Generated by Django 4.2.7 on 2025-02-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=10, unique=True)),
                ('profile_pic', models.ImageField(upload_to='profilepic')),
                ('medical_report', models.ImageField(blank=True, default=None, null=True, upload_to='medicalreport')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Select', 'Select'), ('Male', 'Male'), ('Female', 'Female')], default='Select', max_length=6)),
                ('height', models.DecimalField(decimal_places=2, default=None, help_text='Height in centimeters', max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, default=None, help_text='Weight in kilograms', max_digits=5)),
                ('blood_group', models.CharField(choices=[('Select', 'Select'), ('A+', 'A Pos'), ('A-', 'A Neg'), ('B+', 'B Pos'), ('B-', 'B Neg'), ('AB+', 'Ab Pos'), ('AB-', 'Ab Neg'), ('O+', 'O Pos'), ('O-', 'O Neg')], default='Select', max_length=6)),
                ('department', models.CharField(choices=[('Select', 'Select'), ('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Orthopedics', 'Orthopedics'), ('Pediatrics', 'Pediatrics'), ('Oncology', 'Oncology'), ('Dermatology', 'Dermatology'), ('Gynecology', 'Gynecology'), ('ENT', 'ENT')], help_text="Select the doctor's department", max_length=20)),
                ('years_of_experiance', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('license_number', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('license_photo', models.ImageField(blank=True, default=None, null=True, upload_to='licensephoto')),
                ('consultation_fee', models.IntegerField(blank=True, default=None, null=True)),
                ('upi_id', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_doctor', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
