# Generated by Django 4.2.7 on 2025-05-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wallet',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='slot',
            field=models.CharField(choices=[('09:00 am - 10:00 am', '09:00 am - 10:00 am'), ('10:00 am - 11:00 am', '10:00 am - 11:00 am'), ('11:00 am - 12:00 pm', '11:00 am - 12:00 pm'), ('12:00 pm - 1:00 pm', '12:00 pm - 1:00 pm'), ('1:00 pm - 2:00 pm', '1:00 pm - 2:00 pm'), ('2:00 pm - 3:00 pm', '2:00 pm - 3:00 pm'), ('3:00 pm - 4:00 pm', '3:00 pm - 4:00 pm'), ('4:00 pm - 5:00 pm', '4:00 pm - 5:00 pm'), ('5:00 pm - 6:00 pm', '5:00 pm - 6:00 pm'), ('6:00 pm - 7:00 pm', '6:00 pm - 7:00 pm'), ('7:00 pm - 8:00 pm', '7:00 pm - 8:00 pm'), ('8:00 pm - 9:00 pm', '8:00 pm - 9:00 pm')], help_text='Select the available time slot (each slot is one hour)', max_length=19),
        ),
    ]
