# Generated by Django 4.2.7 on 2025-03-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_doctoravailability_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='earning',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
