# Generated by Django 4.2.7 on 2025-03-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_doctoravailability_room_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='meet_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
