# Generated by Django 4.2.7 on 2025-03-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_doctoravailability_earning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctoravailability',
            old_name='earning',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
    ]
