# Generated by Django 4.2.7 on 2025-03-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_doctoravailability_meet_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
