# Generated by Django 4.2.7 on 2025-03-25 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_earning_doctoravailability_amount_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together=set(),
        ),
    ]
