# Generated by Django 4.2.7 on 2025-03-01 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_userprofile_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of availability')),
                ('slot', models.CharField(choices=[('09:00', '09:00-10:00'), ('10:00', '10:00-11:00'), ('11:00', '11:00-12:00'), ('12:00', '12:00-11:00'), ('1:00', '1:00-2:00'), ('2:00', '2:00-3:00'), ('3:00', '3:00-4:00'), ('4:00', '4:00-5:00'), ('5:00', '5:00-6:00'), ('6:00', '6:00-7:00'), ('7:00', '7:00-8:00'), ('8:00', '8:00-9:00')], help_text='Select the available time slot (each slot is one hour)', max_length=5)),
                ('is_available', models.BooleanField(default=True, help_text='Indicates if the doctor is available during this slot')),
                ('doctor', models.ForeignKey(limit_choices_to={'is_doctor': True}, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'slot'],
                'unique_together': {('doctor', 'date', 'slot')},
            },
        ),
    ]
