# Generated by Django 4.2.7 on 2025-03-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_doctoravailability_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=9),
        ),
    ]
