# Generated by Django 4.2.7 on 2025-03-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_doctoravailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='slot',
            field=models.CharField(choices=[('09:00', '09:00-10:00'), ('10:00', '10:00-11:00'), ('11:00', '11:00-12:00'), ('12:00', '12:00-1:00'), ('1:00', '1:00-2:00'), ('2:00', '2:00-3:00'), ('3:00', '3:00-4:00'), ('4:00', '4:00-5:00'), ('5:00', '5:00-6:00'), ('6:00', '6:00-7:00'), ('7:00', '7:00-8:00'), ('8:00', '8:00-9:00')], help_text='Select the available time slot (each slot is one hour)', max_length=5),
        ),
    ]
