# Generated by Django 4.2.7 on 2025-03-25 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_doctoravailability_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctoravailability',
            old_name='isDelete',
            new_name='isDeleted',
        ),
    ]
