# Generated by Django 4.2.7 on 2025-04-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_userprofile_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
