# Generated by Django 4.2.7 on 2025-04-07 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_userprofile_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table=None,
        ),
    ]
